// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// newCalcEnrichmentScoreCPP
double newCalcEnrichmentScoreCPP(IntegerVector Set, NumericVector Eso, double exponent, bool shuffle);
RcppExport SEXP _DeepCCv2_newCalcEnrichmentScoreCPP(SEXP SetSEXP, SEXP EsoSEXP, SEXP exponentSEXP, SEXP shuffleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type Set(SetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Eso(EsoSEXP);
    Rcpp::traits::input_parameter< double >::type exponent(exponentSEXP);
    Rcpp::traits::input_parameter< bool >::type shuffle(shuffleSEXP);
    rcpp_result_gen = Rcpp::wrap(newCalcEnrichmentScoreCPP(Set, Eso, exponent, shuffle));
    return rcpp_result_gen;
END_RCPP
}
// single_newCalcEnrichmentScoreCPP
double single_newCalcEnrichmentScoreCPP(IntegerVector Set, NumericVector Eso, double exponent, int times);
RcppExport SEXP _DeepCCv2_single_newCalcEnrichmentScoreCPP(SEXP SetSEXP, SEXP EsoSEXP, SEXP exponentSEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type Set(SetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Eso(EsoSEXP);
    Rcpp::traits::input_parameter< double >::type exponent(exponentSEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    rcpp_result_gen = Rcpp::wrap(single_newCalcEnrichmentScoreCPP(Set, Eso, exponent, times));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DeepCCv2_newCalcEnrichmentScoreCPP", (DL_FUNC) &_DeepCCv2_newCalcEnrichmentScoreCPP, 4},
    {"_DeepCCv2_single_newCalcEnrichmentScoreCPP", (DL_FUNC) &_DeepCCv2_single_newCalcEnrichmentScoreCPP, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_DeepCCv2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
