# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

newCalcEnrichmentScoreCPP <- function(Set, Eso, exponent, shuffle = FALSE) {
    .Call('_DeepCCv2_newCalcEnrichmentScoreCPP', PACKAGE = 'DeepCCv2', Set, Eso, exponent, shuffle)
}

single_newCalcEnrichmentScoreCPP <- function(Set, Eso, exponent, times = 1000L) {
    .Call('_DeepCCv2_single_newCalcEnrichmentScoreCPP', PACKAGE = 'DeepCCv2', Set, Eso, exponent, times)
}

